version: '3.0'

services:
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/rental-cars-treina-dev-1
    ports: 
      - "3000:3000"
      - "8808:8808"
    links: 
      - db
      - sidekiq
    environment:
      REDIS_URL: "redis://redis:6379/12"

  db:
    image: postgres:12.1
    volumes:
      - ./tmp/db:/var/lib/postgresql/data

  redis:
    image: redis
    volumes:
      - ./tmp/db:/var/lib/redis/data

  sidekiq:
    build: .
    command: 'bundle exec sidekiq'
    volumes:
      - .:/rental-cars-treina-dev-1
    environment:
      REDIS_URL: "redis://redis:6379/12"
    depends_on:
      - redis
